spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=PostgreSQL;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
  h2:
    console:
      enabled: true